"""add jti to refresh tokens

Revision ID: 21fa4ae8b1cc
Revises: 5c7d998f685a
Create Date: 2026-07-05 18:58:17.500807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fa4ae8b1cc'
down_revision: Union[str, Sequence[str], None] = '5c7d998f685a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'refresh_tokens' AND column_name = 'jti') THEN ALTER TABLE refresh_tokens ADD COLUMN jti VARCHAR(36) NOT NULL; END IF; END $$;"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'jti')
    # ### end Alembic commands ###
