"""add_google_oauth_columns

Revision ID: 487eb0ed5647
Revises: 54a7fb8168af
Create Date: 2026-07-09 16:31:32.815301

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "487eb0ed5647"
down_revision: str | None = "54a7fb8168af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE (table_schema = 'authentication' OR table_schema = 'public') AND table_name = 'users' AND column_name = 'google_id') THEN IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'authentication' AND tablename = 'users') THEN ALTER TABLE authentication.users ADD COLUMN google_id VARCHAR(255) NULL; ELSE ALTER TABLE public.users ADD COLUMN google_id VARCHAR(255) NULL; END IF; END IF; END $$;"
    )
    op.execute(
        "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'authentication' AND tablename = 'users') THEN ALTER TABLE authentication.users ALTER COLUMN hashed_password DROP NOT NULL; ELSE ALTER TABLE public.users ALTER COLUMN hashed_password DROP NOT NULL; END IF; END $$;"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
