"""add_lockout_columns_to_users

Revision ID: 54a7fb8168af
Revises: 526b088ddfed
Create Date: 2026-07-09 14:42:28.689132

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "54a7fb8168af"
down_revision: str | None = "526b088ddfed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add failed_login_attempts with server_default so existing rows get 0
    op.add_column(
        "users",
        sa.Column(
            "failed_login_attempts",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    # Remove the server_default so the column behaves as application-managed
    op.alter_column("users", "failed_login_attempts", server_default=None)
    op.add_column(
        "users",
        sa.Column("lockout_until", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "lockout_until")
    op.drop_column("users", "failed_login_attempts")
    # ### end Alembic commands ###
