"""add_lockout_columns_to_users

Revision ID: 54a7fb8168af
Revises: 526b088ddfed
Create Date: 2026-07-09 14:42:28.689132

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54a7fb8168af"
down_revision: str | None = "526b088ddfed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'failed_login_attempts') THEN ALTER TABLE users ADD COLUMN failed_login_attempts INTEGER NOT NULL DEFAULT 0; ALTER TABLE users ALTER COLUMN failed_login_attempts DROP DEFAULT; END IF; END $$;"
    )
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'lockout_until') THEN ALTER TABLE users ADD COLUMN lockout_until TIMESTAMP WITH TIME ZONE NULL; END IF; END $$;"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "lockout_until")
    op.drop_column("users", "failed_login_attempts")
    # ### end Alembic commands ###
